#115 check and update hazard model
Deltares/hydromt_fiat pull request #151
Opened 2023-10-04 14:26 UTC by Mares2022

The set up hazard was updated to create netcdf files with multiple bands pero return period map. The update integrates a small functionality to sorte the return period maps from the lower return period to the highest return period. Some check function as check_files functions and check_param_type  were removed or modified to avoid redundancy in the data checks. This included removing functions from validation.py. Functions to create list of parameters and check their size are still in the code. Data catalog is not used anymore in the set up hazard workflow so parameter catalog_name and its connections were removed.

2023-10-04 14:30 UTC, Mares2022 commented
Please add comments on how to improve the tests for the hazard components. I still miss to improve the tests. An addition point is that for one reason, when working with geotiffs the running time of the test is huge which makes me think that there is a wrong writing of the grid data. I already checked the data structure of the outputs but I require to check the spatial distribution of the maps (using qgis) to check if it is correct.

2023-10-04 14:32 UTC, Mares2022 commented
Test_hazard.py was erased in the current branch so we can erase it again in fiat_integrator.

2023-10-04 15:27 UTC, frederique-hub requested changes

2023-10-16 07:23 UTC, Mares2022 commented on hydromt_fiat/fiat.py
> +
I removed all the sfinc components. This is a task that can be done through hydromt sfincs. I kept "da = da * unit_conversion_factor"  from here as a general check.

2023-10-16 07:25 UTC, Mares2022 commented on hydromt_fiat/workflows/hazard.py
> +    #TODO: remove this function
The function was required partially. That is why par of it is still there, but a significant part was removed in hazard.py and validation.py. This function was modified to only produce a list of parameters, the check of data was already removed.

2023-10-16 07:25 UTC, Mares2022 commented on hydromt_fiat/fiat.py
> +                "analysis": "event",
I will coordinate with Brandon. Attributes could be skipped in this dataset as the return period is written in the bands name of the dataset. I changed it as rp meanwhile.

2023-10-16 08:18 UTC, Mares2022 commented
This branch can already be merged, it addresses Dirk's comments. The only comment missing is this one: https://github.com/Deltares/hydromt_fiat/pull/124#discussion_r1360250835. We have to ensure that self.region exists to load raster data with the parameter geoms=self.region. At this moment, with the current test, it is working. I also need to improve the test, let me know what is missing. I removed the test for sfincs maps as they are not read anymore through hydromt fiat. The process of this sfincs.nc maps can be done through hydromt sfincs.

2023-10-16 09:23 UTC, frederique-hub commented
Great! I will merge this branch into fiat_integrator to have everything there. We will discuss the remaining things tomorrow and add issues for those things if required. Good work!

2023-10-16 09:34 UTC, merged