#177 aggregation output = # 153 BF output
Deltares/hydromt_fiat pull request #224
Opened 2023-12-12 08:03 UTC by Santonia27

Create folder in Output directory for building footprints and aggregation zones/ additional attributes

2023-12-12 08:04 UTC, Santonia27 commented
Is it possible to have multiple BF?  Currently code set up for a single one. 

If multiple BF can be added I need to add if-statement like in additional attributes.

2023-12-13 12:20 UTC, frederique-hub commented
> Is it possible to have multiple BF? Currently code set up for a single one.
> 
> If multiple BF can be added I need to add if-statement like in additional attributes.

Just one is good!!

2023-12-13 12:25 UTC, frederique-hub requested changes

2023-12-13 12:25 UTC, frederique-hub commented on hydromt_fiat/fiat.py
> +            shutil.copy2(aggregation_area_fn, additional_att)
```suggestion
```
Just saving it in the additional_attributes folder in the root folder is sufficient!

2023-12-13 12:25 UTC, frederique-hub commented on hydromt_fiat/fiat.py
> +            shutil.copy2(building_footprint_fn, building_footprints_out)
```suggestion
```
It is sufficient to only save the building footprints in the exposure/building_footprints folder

2023-12-13 12:38 UTC, frederique-hub approved these changes

2023-12-13 12:55 UTC, merged